// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJAr-3cjKWvhvL2MsO235gu9PGtXufAUA',
    appId: '1:320017802508:web:9f02efbe936ee80f661529',
    messagingSenderId: '320017802508',
    projectId: 'bustracking-d6235',
    authDomain: 'bustracking-d6235.firebaseapp.com',
    storageBucket: 'bustracking-d6235.firebasestorage.app',
    measurementId: 'G-8R1VWLW84Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoljhuzuRJPTsCpscR8R6wvwA_y_m7bdI',
    appId: '1:320017802508:android:829bae6069d8cee6661529',
    messagingSenderId: '320017802508',
    projectId: 'bustracking-d6235',
    storageBucket: 'bustracking-d6235.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdWLw2QgFwvphxggSw-rb9sAjvnHlrgRM',
    appId: '1:320017802508:ios:22638ac75b01398f661529',
    messagingSenderId: '320017802508',
    projectId: 'bustracking-d6235',
    storageBucket: 'bustracking-d6235.firebasestorage.app',
    iosBundleId: 'com.example.bustracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdWLw2QgFwvphxggSw-rb9sAjvnHlrgRM',
    appId: '1:320017802508:ios:22638ac75b01398f661529',
    messagingSenderId: '320017802508',
    projectId: 'bustracking-d6235',
    storageBucket: 'bustracking-d6235.firebasestorage.app',
    iosBundleId: 'com.example.bustracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJAr-3cjKWvhvL2MsO235gu9PGtXufAUA',
    appId: '1:320017802508:web:9d367b9819772c13661529',
    messagingSenderId: '320017802508',
    projectId: 'bustracking-d6235',
    authDomain: 'bustracking-d6235.firebaseapp.com',
    storageBucket: 'bustracking-d6235.firebasestorage.app',
    measurementId: 'G-9LY5MTCEVX',
  );
}
